name: GitHub Actions Demo

on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "name of the event that triggered the workflow - ${{ github.event_name }}"
      - run: echo "name of the branch that the repository is currently referencing ${{ github.ref }}"
      - uses: actions/checkout@v3.3.0
      - name: List all files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
